[server]
address="0.0.0.0:8080"
staticPrefix="/s/"
staticRoot="/Users/eric/prj/chariot/chariotday/pongish/static"
templateRoot="/Users/eric/prj/chariot/chariotday/pongish/templates"
wsCheckOrigin=false

[client]
websocketGameEndpoint="ws://192.168.1.157:8080/game"
